### PR TITLE
Removed lines with ##

### PR DESCRIPTION
**Pull request by sbahinip**

### CODE REVIEW

**Comment by nsahoo** [comment]
@sbahinip : I can still there is something like "<<<<<<< HEAD". Did you put it knowingly ? If not, I would request you to remove it before doing the PR. 

N.B: Always give a final look before doing the PR, otherwise you have to do it multiple times.

**Comment by sbahinip** [comment]
No, I didn't put it knowingly. Don't know why it was there. I have removed it and resubmitted. Hope it worked.

**Comment by nsahoo** [comment]
@sbahinip : since you do the PR two times on top of each other, there was some problem in merging the PR. So I made some (minor) changes to make it merge. DON'T MAKE SEVERAL PRs FOR A SINGLE CHANGE.

**Comment by nsahoo** [comment]
👍 (merged)

**Pull request merged**
