### PR TITLE
added phimumu mc sample luminosity calculation textfile

### PR DESCRIPTION
**Pull request by deepaksahoo89**
@nsahoo please review it.

### CODE REVIEW

**Comment by nsahoo** [comment]
@deepaksahoo89 : can't you put in one .txt file the luminosities for both data and mc ? Why three separate .txt files for MC ?

**Comment by nsahoo** [comment]
@deepaksahoo89 : sorry, I didn't get time to review it. I'll merge this PR ASAP.

**Comment by sbahinip** [comment]
I checked the calculations. All are correct, except for Phimumu MC version2(extended version).
It should be 36061.009 fb-1 instead of 36061.008 fb-1.

**Comment by nsahoo** [comment]
@sbahinip : thanks a lot for the x-check. The 3rd decimal point doesn't matter so much. Of course it would be good to put the right number.

@deepaksahoo89 : can you edit and push it again ?

**Comment by deepaksahoo89** [comment]
I have edited and pushed it.

**Pull request merged**
