### PR TITLE
Pull selector

### PR DESCRIPTION
**Pull request by deepaksahoo89**

### CODE REVIEW

**Comment by nsahoo** [comment]
@deepaksahoo89 : did you check the produced NTuple's content ? Everything filled correctly ?

**Comment by deepaksahoo89** [comment]
Yes

**Comment by nsahoo** [comment]
@deepaksahoo89: OK, let me review it now.

**Comment by nsahoo** [comment]
@deepaksahoo89 : I see you've made few changes regarding the counters and why did you remove the tag "mc.hlt" ? I said during today's chat that we are not going to use this tag anyway, but keep it there. The main concern is that if you are processing a root file with a certain tag, it should contain the necessary GEN variables, not additional ones which are not really required. So I would request to put back "mc.hlt" tag in the selector code for book-keeping purpose.

**Comment by deepaksahoo89** [comment]
I have added mc.hlt tag

**Comment by nsahoo** [comment]
@deepaksahoo89: I tried to do "make" by pulling the new selector from your branch, but it shows the error. Could you check with a fresh start w/o any CMSSW release because in principle it should be independent of any CMSSW framework ?

[nsahoo@lxplus001 plugins]$ make
g++ -Wall -g `root-config --cflags --libs` -lProof SingleBsToPhiMuMuSelector.cc -o sel
SingleBsToPhiMuMuSelector.cc:23:20: error: TProof.h: No such file or directory
SingleBsToPhiMuMuSelector.cc: In member function ‘virtual void SingleBsToPhiMuMuSelector::Terminate()’:
SingleBsToPhiMuMuSelector.cc:393: warning: unknown conversion type character 0xa in format
SingleBsToPhiMuMuSelector.cc:395: warning: unknown conversion type character 0xa in format
SingleBsToPhiMuMuSelector.cc:397: warning: unknown conversion type character 0xa in format
SingleBsToPhiMuMuSelector.cc:398: warning: unknown conversion type character 0xa in format
SingleBsToPhiMuMuSelector.cc: In function ‘int main(int, char**)’:
SingleBsToPhiMuMuSelector.cc:692: error: ‘TProof’ has not been declared
SingleBsToPhiMuMuSelector.cc:716: warning: comparison with string literal results in unspecified behaviour
SingleBsToPhiMuMuSelector.cc:723: error: ‘gSystem’ was not declared in this scope
make: *** [sel] Error 1
[nsahoo@lxplus001 plugins]$

**Comment by deepaksahoo89** [comment]
@nsahoo, I cloned the branch in a different directory. I did make without any CMSSW. It is compiling.There is no error.

**Comment by nsahoo** [comment]
@deepaksahoo89 : could you please put the steps  what you followed ? I can check accordingly.

**Comment by nsahoo** [comment]
@deepaksahoo89 : I made it run but I observed many issues in the code
1. the counters are missing (in some tags it's there, whereas not in others)
2. tag "cutfom" is giving the same result as tag "cut0", how come ? What's the motivation for tag "cutfom" ? Did you use these ntuples (after processing with "cutfom" tag) for FOM studies ?

So I can't merge it till the above issues are resolved, sorry !

**Comment by deepaksahoo89** [comment]
@nsahoo 
1. The counters are there. Could you please point me where counter is not there?
2.cutfom tag is with only softmuon id no best vertex selection. cut0 tag is with softmuon id and best vertex selection.Yes, I have used ntuples with cutfom tag for FOM studies.

**Comment by nsahoo** [comment]
+1 (merged)

**Pull request merged**
