### PR TITLE
[merged] additional branches saved for different trigger categories

### PR DESCRIPTION
**Pull request by nsahoo**
Additional variables/branches saved in the tuple for different trigger categories used while tuple processing. These additional branches are:
Trig_LMNR , Trig_JPSI  and Trig_PSIP meant for LMNR+trk, JPSi+trk and PSi'+trk trigger categories. 
They are set to 1 for events passing each individual triggers. 

Please find some validation plots below. 

-  ### [ signal mc, full q2 region with individual triggers cut applied ]

Screen Shot 2020-01-23 at 12 30 23 AM

-  ### [ signal mc, full q2 region with triggers cut applied ]

Screen Shot 2020-01-23 at 12 30 52 AM

-  ### [ signal mc, full q2 region with LMNR triggers cut applied ]

Screen Shot 2020-01-23 at 12 32 22 AM 1

-  ### [ signal mc, full q2 region with PSI resonant triggers cut applied ]

Screen Shot 2020-01-23 at 12 33 02 AM

- ### [ signal mc, plotting "triggers" variable ]

Screen Shot 2020-01-23 at 12 45 48 AM

- ### [ signal mc, why triggers variable shows value == 2 ? ]
Screen Shot 2020-01-23 at 12 46 43 AM

This is because the PSi' trigger does trigger up to ~4.1 GeV/c2 where LMNR trigger also overlaps, that's why for these small fraction of events we are getting triggers==2. There is NOTHING wrong. It's completely understood. 

My conclusion: I won't expect any dip in dimuon mass or q2 plots (which was forwarded by Samarendra today). 

Please do let me know your point-of-view, you can write your comments below. If you're fully convinced, I'll merge this PR.

n.

### CODE REVIEW

**Comment by sbahinip** [comment]
The Psi' trigger trigger is between 3.3 - 4.0 GeV. So, I do not understand the events with trigger 2.
But, I do not see any dip at the trigger intersections in these plots.

**Comment by sbahinip** [comment]
I think the dip he sees could be due to the J/psi and psi' rejection cuts. Probably, he has made them more tight as compared to us.

**Comment by nsahoo** [comment]
Yes, but if he applies the PSi rejection cuts, then the corresponding q2 regions will not show up because you're rejecting all events there. 
@Rishabh and @Samarendra: can you guys check this ?

**Comment by nsahoo** [comment]
👍

**Pull request merged**
